config/routes.rb
MusicSurvey::Application.routes.draw do
  resources :records
  
  match '/thank_you' => 'pages#thank_you'
  

  root :to => 'records#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def thank_you
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # GET /records
  # GET /records.json
  def index
    @records = Record.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    second = Time.now.sec
    @music_bool = (second % 4) < 2
    @order_bool = second % 2 == 1
    @record = Record.new :music => @music_bool, :order => @order_bool

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(params[:record])

    respond_to do |format|
      if @record.save
        # format.html { redirect_to @record, :notice => 'Record was successfully created.' }
        format.html { redirect_to "/thank_you", :notice => 'Record was successfully created.' }
        format.json { render :json => @record, :status => :created, :location => @record }
      else
        format.html { render :action => "new" }
        format.json { render :json => @record.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record, :notice => 'Record was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @record.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicSurvey</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="body">
  <h1>Music Survey: Part 2</h1>
  <br>
  <div id="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="problem_one_questions">
    <div class="field">
      <%= f.label :name, "AP only occurs in trained musicians." %><br />
      <%= f.radio_button :p1a1, "true" %>
      <%= label :p1a1_true, 'True', :value=>"true" %>
      <%= f.radio_button :p1a1, "false" %>
      <%= label :p1a1_false, 'False', :value=>"false" %>
    </div>
    <div class="field">
      <%= f.label :name, "People with AP are able to control when they want to identify a pitch and when they don’t." %><br />
      <%= f.radio_button :p1a2, "true" %>
      <%= label :p1a2_true, 'True', :value=>"true" %>
      <%= f.radio_button :p1a2, "false" %>
      <%= label :p1a2_false, 'False', :value=>"false" %>
    </div>
    <div class="field">
      <%= f.label :name, "The act of transposing music is difficult for people with AP." %><br />
      <%= f.radio_button :p1a3, "true" %>
      <%= label :p1a3_true, 'True', :value=>"true" %>
      <%= f.radio_button :p1a3, "false" %>
      <%= label :p1a3_false, 'False', :value=>"false" %>
    </div>
    <div class="field">
      <%= f.label :name, "Our brains break down visual information and auditory information in a similar way." %><br />
      <%= f.radio_button :p1a4, "true" %>
      <%= label :p1a4_true, 'True', :value=>"true" %>
      <%= f.radio_button :p1a4, "false" %>
      <%= label :p1a4_false, 'False', :value=>"false" %>
    </div>
    <div class="field">
      <%= f.label "The phenomenon of AP may be explained by differences in brain structures" %><br />
      <%= f.radio_button :p1a5, "true" %>
      <%= label :p1a5_true, 'True', :value=>"true" %>
      <%= f.radio_button :p1a5, "false" %>
      <%= label :p1a5_false, 'False', :value=>"false" %>
    </div>
  </div>
  
  <div id="problem_two_questions">
    <div class="field">
      <%= f.label "Scientific discoveries of anatomical differences in musicians’ brains began in the 19th century and continue today." %><br />
      <%= f.radio_button :p2a1, "true" %>
      <%= label :p2a1_true, 'True', :value=>"true" %>
      <%= f.radio_button :p2a1, "false" %>
      <%= label :p2a1_false, 'False', :value=>"false" %>
    </div>
    <div class="field">
      <%= f.label "Musicians have asymmetry in the planum temporale, with the right side usually being larger than the left." %><br />
      <%= f.radio_button :p2a2, "true" %>
      <%= label :p2a2_true, 'True', :value=>"true" %>
      <%= f.radio_button :p2a2, "false" %>
      <%= label :p2a2_false, 'False', :value=>"false" %>
    </div>
    <div class="field">
      <%= f.label "Generally, the earlier the person began musical training, the greater asymmetry was noticed in hand skills." %><br />
      <%= f.radio_button :p2a3, "true" %>
      <%= label :p2a3_true, 'True', :value=>"true" %>
      <%= f.radio_button :p2a3, "false" %>
      <%= label :p2a3_false, 'False', :value=>"false" %>
    </div>
    <div class="field">
      <%= f.label "The size of the planum temporale is a commonly used measure of dominance in the brain." %><br />
      <%= f.radio_button :p2a4, "true" %>
      <%= label :p2a4_true, 'True', :value=>"true" %>
      <%= f.radio_button :p2a4, "false" %>
      <%= label :p2a4_false, 'False', :value=>"false" %>
    </div>
    <div class="field">
      <%= f.label "Asymmetries in several brain areas (corpus callosum, primary motor cortex, etc) have been most pronounced between non-AP musicians and AP musicians." %><br />
      <%= f.radio_button :p2a5, "true" %>
      <%= label :p2a5_true, 'True', :value=>"true" %>
      <%= f.radio_button :p2a5, "false" %>
      <%= label :p2a5_false, 'False', :value=>"false" %>
    </div>
  </div>
  
  <div id="username_field">
    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
  </div>
  <div id="submit_button">
    Did something go wrong? Please let me know if the music didn't play or if there was something that didn't work or seemed to work incorrectly.
    <div class="field">
      <%= f.label :comment %>
      <%= f.text_area :comment%>
    </div>
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  </div>
  
  <div id="music"> <%= @music_bool %> </div>
  <div id="order"> <%= @order_bool %> </div>
  
  <div id="metadata">
    <div class="field">
      <%= f.label :music %><br />
      <%= f.check_box :music %>
    </div>
    <div class="field">
      <%= f.label :order %><br />
      <%= f.check_box :order %>
    </div>
  <div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<div style="font-style:italic">
Thank you very much for completing the survey in Part 1. This is the second and final portion of the survey, and will last 6 minutes total. 
</div>
<br>
You will be presented with <span style="color:#1E487D;font-weight:bold;">two passages</span> to read, and several short questions to answer about the passages. <span style="color:#548DD4">Music will be playing in the background for one of the two passages</span>. It may be on the first passage or the second passage. 
<br>
<br>
<span style="font-weight:bold">Before beginning:</span>
<br>
<span >Please test your speakers/headphones</span> so that the music you hear is at a medium noise level : that is, loud enough so you can hear it, but also soft enough so you could hear someone sitting at an arms length away. Please ensure that the area around you is as quiet as possible, besides the background music. Use the following audio clip to test the volume of your speakers/headphones.
<br>
<br>
<div id="play_stop_button" class="button">Play/Stop</div>
<br>
<br>
<span style="font-weight:bold">Once you begin:</span>
<br>
You will be presented with a passage to read, and will be given 2 minutes to read it. (There will be a timer at the top of the screen.)
After 2 minutes, you will be presented with 5 True/False questions on the passage. You will have 1 minute to complete these. Please answer all five questions. 
You will then be shown a second passage to read, and will be given 2 minutes to read it. 
Following that, there will be 5 True/False questions on the second passage. You will again have 1 minute to complete them. 
<br><br>
<div class="button" id="next">
<%= link_to 'Next', new_record_path %>
</div>
<br>
<div id="sound_element"></div>

app/views/records/new.html.erb
<h2 id="countdown">
</h2>

<h1 id="title"></h1>

<div id="sound_element"></div>

<div id="problem_one_passage">
   The study of the memory codes used for musical pitch is one of the oldest in experimental psychology, beginning with Helmholtz, Fechner, Stumpf and Wundt. Indeed, the Gestalt psychology movement was launched with the following question: how is it that a melody composed of specific musical pitches retains its identity despite transposition and when none of the original pitches are present? A related question is that of why some people are able to label all the notes of the musical scale as effortlessly as most of us label colors – a phenomenon known as absolute pitch (AP). Recent findings from neuroimaging, psychophysics, developmental psychology and cognitive science are converging to create a critical mass of knowledge on which to build new theories and experiments. 
   <br><br>
   Research on absolute pitch has grown exponentially over the past 120 years. Defined as the ability either to identify the chroma (pitch class) of a tone presented in isolation or to produce a specified pitch without external reference, AP occurs in 1 in 10,000 people. People with AP presumably possess an internal template to map musical tones to linguistic labels. Sometimes regarded as a mark of musicianship, AP is in fact largely irrelevant to most musical tasks. Being unable to turn it off, possessors of AP perform dramatically poorer at judging whether a melody and its transposed counterpart are the same, a task that non-AP musicians accomplish with ease. 
   <br><br>
   Comparisons are often made between color labelling in most humans and pitch labelling in AP possessors, because AP possessors categorize and label pitches quite effortlessly and automatically. However, the human visual system is constructed in such a way as to allow discrete categories to emerge readily: information about color is separated into three (or sometimes four) streams by cones in the retina, and remains separated up to the cortex. By contrast, information from the cochlea and peripheral auditory system is much more continuous and lacks the one-to-one mapping between excitation patterns and percepts. Accordingly, pitch and color perception are phenomenologically different: colors are experienced as belonging to categories; pitches are experienced (by most of us) as continuous. The fact that some individuals place pitches into categories requires explanation of what is different about these individuals in their development or neural architecture. 
</div>

<div id="problem_two_passage">
  Since the age of phrenology, neuroscientists have tried to relate extraordinary skills to changes in brain anatomy. For example, at the beginning of the twentieth century, Auerbach reported that the middle and posterior thirds of the superior temporal gyrus were larger than normal in several post-mortem studies of the brains of famous musicians. Modern brain-imaging techniques, such as high-resolution magnetic resonance imaging (MRI), allow us to study anatomical details in the brains of living humans. Studies in which these techniques have been used have shown that several brain areas, including the planum temporale, the anterior corpus callosum, the primary hand motor area and the cerebellum, differ in their structure and size between musicians and control subjects. These findings have reopened the debate about whether these structural differences are related directly to musical ability. 
  <br><br>
  Asymmetry of the planum temporale has been suggested as a marker of cerebral dominance, because its direction and size correlate with handedness. In two independent samples, musicians with absolute pitch (AP) had a more pronounced leftward planum temporale asymmetry than did musicians with relative pitch (RP) or non-musician controls; another study found no significant difference in planum temporale volume between musicians with AP and those with RP. However, when compared with a large sample of right-handed non-musician controls, musicians with AP again showed a larger left planum temporale. 
  <br><br>
  Amunts and colleagues have estimated the size of the primary hand motor area by determining the intrasulcal length of the posterior bank of the precentral gyrus in linearly normalized MRI images. Musicians had a greater intrasulcal length on both sides, but more so on the right, non-dominant hemisphere, resulting in reduced asymmetry scores for this area in musicians. There was a strong negative correlation between the time at which musical training had begun and the size of the right- and left-hand motor areas. This was reflected behaviourally by reduced asymmetry in measurements of hand skill and a negative correlation between hand-skill asymmetry and the age at which musical training started.   
</div>
<div class="user">
Please re-enter your anonymous id phrase from part 1 of the survey:
</div>
<br>
<input class="user" id="username" type="text"></input>
<br><br>
<div class="user button" id="user_button">
  Submit
</div>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>ID Phrase:</b>
  <%= @record.username %>
</p>

<p>
<b>Comment:</b>
<%= @record.comment %>
</p>

<p>
  <b>Music:</b>
  <%= @record.music %>
</p>

<p>
  <b>Order:</b>
  <%= @record.order %>
</p>

<p>
  <b>P1a1:</b>
  <%= @record.p1a1 %>
</p>

<p>
  <b>P1a2:</b>
  <%= @record.p1a2 %>
</p>

<p>
  <b>P1a3:</b>
  <%= @record.p1a3 %>
</p>

<p>
  <b>P1a4:</b>
  <%= @record.p1a4 %>
</p>

<p>
  <b>P1a5:</b>
  <%= @record.p1a5 %>
</p>

<p>
  <b>P2a1:</b>
  <%= @record.p2a1 %>
</p>

<p>
  <b>P2a2:</b>
  <%= @record.p2a2 %>
</p>

<p>
  <b>P2a3:</b>
  <%= @record.p2a3 %>
</p>

<p>
  <b>P2a4:</b>
  <%= @record.p2a4 %>
</p>

<p>
  <b>P2a5:</b>
  <%= @record.p2a5 %>
</p>


<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>